# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03ad92b4b7e5238e65cd0c12ed8662e11b1986c28aa31925a1d0feeeb8e2baefb0c79cfef7d2d6c35da8f463c5f56d537f81b6289a8333947ad2bbdd1e49e314

test:
  secret_key_base: 0e3d7afdf0be27a76ed75a9a1e425303becf080cd340b4ade4025f6a2c5b2255bd29aa890e4de6032367de2dd6f333e354fcb00fe6bba101bdbbea4da4f321c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
